[project]
name = "flower-viewer-repo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "slpp>=1.2.3",
]
